### PR TITLE
Network plugin 'wait_for_connection'.

### PR DESCRIPTION
**Pull request by pszulczewski**
This plugin is to wait for a host connection before continuing with other tasks.
It is useful when a node is rebooted and nornir needs to wait for a node (or group of nodes) to be back online.

### CODE REVIEW

**Comment by pszulczewski** [comment]
Dear maintainers,

I was playing with tests and wanted to replicate what you have in test_tcp_ping, but my test for a host with opened port 22 is failing.
Would you be able to give me some hints how to use your test inventory to make a test for tcp port reachability?

**Comment by ogenstad** [comment]
Thank you for your contribution. At the moment this won't be merged to this repo due to the changed described in #486. 

Once this has happened a plugin like the one you are contributing will have to live in another repo.

**Comment by pszulczewski** [comment]
Thanks Patrick I understand and I expected that as other PR has been put on hold.

Nevertheless I am curious why one of my tests 
was failing.
When you run tests for tcp_ping, are there any hosts in your test env responding on tcp ports or there some patching/mocking under the hood?

**Comment by dbarrosop** [comment]
We use containers for mocking devices (with the exception of napalm). Check the `docker-compose.yaml` file in the root of the project.

**Comment by ktbyers** [comment]
Closing as this is as it is an old plugin submitted against the core repository.

**Pull request closed without merging**
