### PR TITLE
Adds duplicated code as function for inventory helper.

### LINKED ISSUE #723: Feature Request: Inventory Defaults Loading
It looks like there is some common code being implemented on Nornir NetBox and Nornir Ansible inventories. Which is something that will also be implemented into the Nornir Nautobot inventory as well. This should likely become a method that is common in the Nornir library.

### PR DESCRIPTION
**Pull request by jvanderaa**
## Details

- Takes code that is repeated in multiple inventory files and adds it into the Nornir core inventory
- Credit goes to Nornir NetBox and Nornir Ansible inventories that the content was sourced from
- Adds tests to verify the information

https://github.com/wvandeun/nornir_netbox/blob/develop/nornir_netbox/plugins/inventory/netbox.py#L39-L48
https://github.com/carlmontanari/nornir_ansible/blob/master/nornir_ansible/plugins/inventory/ansible.py#L456-L472

### CODE REVIEW

**Comment by jvanderaa** [comment]
I'm getting this in front of me a bit more. I thought I had something but the tests are not working. So I am going to try to restart the process on another branch.

**Comment by ktbyers** [comment]
@jvanderaa What is the status of this?

Is this dead now i.e. should be closed?

**Comment by jvanderaa** [comment]
Yeah, probably good to close out. Sorry for leaving it for so long @ktbyers

**Comment by ktbyers** [comment]
@jvanderaa No worries at all.

**Pull request closed without merging**
