### PR TITLE
fixes issue with urlencoding for filenames/repository in gitlab

### LINKED ISSUE #454: gitlab plugin _get_repository problem
The problem is function _get_repository search request. If repository path contains group like 'diaspora/diaspora-project-site' search does not work. 
If search only by name 'diaspora-project-site' result may contains list of repo: 
'test/diaspora-project-site'
'diaspora1/diaspora-project-site'
'blabla/diaspora-project-site'
and function return only first PID (project id). 
As said api docs https://docs.gitlab.com/ee/api/projects.html it is posible to use URL-encoded path of the project instead PID.
I will make PR for fix it.

### PR DESCRIPTION
**Pull request by wvandeun**
Fixes an issue with filenames (paths) & namespaced repositories, that contain characters which should be urlencoded.
This PR is basically the same as #455, but it solves some concerns that didn't receive updates.

Fixes #454

### CODE REVIEW

**Comment by k01ek** [comment]
I think, this commit can't fix the problem. In some cases search method will return list of repo. The main problem is using search method instead of using URL-encoded path of the project.

**Comment by wvandeun** [comment]
You are right!
Removed the usage of the search API endpoint now.
Still need to work on updating the documentation.

**Comment by dbarrosop** [comment]
feel free to @ me once this PR is ready and its counterpart has been merged in the other repo :)

Thanks!

**Comment by wvandeun** [comment]
@dbarrosop 
Fighting a bit with black here...
For some reason it considers [this line](https://github.com/nornir-automation/nornir/blob/8f63c796b6b0ea5d57c713490f974448dec5cd2a/tests/plugins/tasks/version_control/test_gitlab.py#L92) not properly formatted. Black would change it to a single line statement, which ends up with a line length which is too long.

**Comment by wvandeun** [comment]
@dbarrosop this one should be good now
3.0 plugin in progress https://github.com/wvandeun/nornir_gitlab

**Pull request merged**
