### PR TITLE
remove support for <py36

### PR DESCRIPTION
**Pull request by dbarrosop**
TODO: Update installation guide

### CODE REVIEW

**Comment by ktbyers** [comment]
+1 except for the Python3.7 not existing on Travis.

**Comment by dbarrosop** [comment]
Ok, will fix that. I want to first merge as many PRs as possible and make a 1.1 release before removing the support though.

**Comment by ogenstad** [comment]
Might be going back and forth with this, but perhaps we should leave 3.4 and 3.5 until we actually start using a 3.6 only feature.

**Comment by ktbyers** [comment]
I suspect PY3.4 is probably pretty close to EOL (given that we now have 3.5, 3.6, and 3.7)...though definite assumption on my part and I couldn't find any exact date on this.

My preference is 3.6 and greater.

**Comment by dbarrosop** [comment]
Yeah, let's stop messing around with this and go directly with py3.6.

**Pull request merged**
