### PR TITLE
Capirca task plugin

### PR DESCRIPTION
**Pull request by fach**
This PR adds a Nornir task plugin for utilizing [Capirca](https://github.com/google/capirca) to generate per-host ACLs. Upon success, the rendered ACL is returned as a string in the result field of a `Result`. For an ACL to be rendered, the plugin must be passed a valid capirca platform type and the host platform must be a target in the specified policy file:
```
header {
  comment:: "Sample multitarget loopback filter"
  target:: juniper LOOPBACK
  target:: arista LOOPBACK
  target:: ciscoxr LOOPBACK
}
```
This platform value is different than the top-level platform inventory field, as the existing inventory values (i.e. junos) didn't map 1:1 to capirca platforms, and maintaining a translation map seemed implicitly terrible. Therefore, the capirca platform type must be explicitly passed but can be included as inventory data as below and passed at task runtime:
```
dev4.group_2:
    data:
        capirca:
            platform: juniper
            expiration: 2
            shade_check: true
            optimize: true
```

The application dependency of Capirca v1.122/latest was left off this PR per the contributing guidelines. Please let me know if you want it added here, in a separate PR or if you will handle it. 

Also, if there is value, I'm happy to add this as a Nornir function as well, which would most likely render and write ACLs to a specified directory, much like the current Capirca toolchain.

### CODE REVIEW

**Comment by fach** [comment]
Checks are failing due to the missing Capirca dependency mentioned above.

**Comment by ktbyers** [comment]
I think I would add the `caprica` dependencies into the `dev` dependencies in pyproject.toml and update the poetry.lock file.

https://github.com/nornir-automation/nornir/blob/develop/pyproject.toml#L44

In other words, make it so the tests/CI-CD can work, but so that end-users are not required to install this dependency.

Others can chime in if they don't like this pattern.

We possibly need a more modular way to manage dependencies for plugins.

**Comment by fach** [comment]
Alright, I did the thing. Travis is happy now.

**Comment by dmfigol** [comment]
@fach thank you for the contribution, Steve! We are right now discussing where the plugins should live #486 and it is very likely that we will end up separating them from the core. Hence at this point, I think it makes sense to hold onto this PR.

**Comment by fach** [comment]
Sounds good. Happy to be a trailblazer with this PR and help get boiler plate going if we want to move plugins outside of the core repo.

**Comment by dbarrosop** [comment]
If you haven't look at #492 and #486 and feel free to provide feedback on the new nornir_napalm repo which I am using to experiment how a plugin repo could look like

**Comment by ktbyers** [comment]
I am going to close this PR as it is no longer applicable to nornir-core (i.e. it should be in its own separate nornir plugin repository).

**Pull request closed without merging**
