### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by jimmelville**

### CODE REVIEW

**Comment by ktbyers** [comment]
Test failure looks to be totally unrelated to your change.

**Comment by jimmelville** [comment]
Just looking to start contributing, just some edits in a text file. I made
these changes via github which created a branch and a PR for me. Please
point me in the right direction if I created this issue

**Comment by ktbyers** [comment]
No I am pretty sure the issue is totally unrelated to your changes and is caused by something else.

**Comment by dbarrosop** [comment]
Thanks!

**Pull request merged**
