### PR TITLE
Implement django style queries

### PR DESCRIPTION
**Pull request by dbarrosop**
Alternative to #149 

So for fun I implemented this. Thoughts? This way the easiest way to implement this I could think of.

### CODE REVIEW

**Comment by dbarrosop** [comment]
@ktbyers @ogenstad

**Comment by ogenstad** [comment]
For me, it was mostly the fact that if we say to people that this will be easy that these filters look different than more simple ones. Perhaps I should just have more faith in humanity. :)

Currently this works:
```python
routers = nr.filter(groups__contains="routers")
```
In #149, there was talk about also having something like this:

```python
routers = nr.filter(groups__not__contains="switches")
```

I think something along those lines would be good to have too.

**Comment by dbarrosop** [comment]
> For me, it was mostly the fact that if we say to people that this will be easy that these filters look different than more simple ones. Perhaps I should just have more faith in humanity. :)

Well, the simple ones still work. This is just if you need it, if you don't nothing changes.

> `routers = nr.filter(groups__not__contains="switches")`

Makes sense, will look into it, the CI is also broken because py2.7 is not nearly as nice as py3 as well so I have to fix it... I can't wait to get rid of py2.7. Should we drop support? :P (not kidding)

**Comment by ogenstad** [comment]
Yeah saw that the old stuff works which is nice.

Since we have a real version out that is installable with pip for Python 2.7 which works quite nicely I'm fine with dropping support for it. In this case it would complicate the code to keep it in which isn't very attractive.

**Comment by ktbyers** [comment]
@dbarrosop Dropping PY27 support is fine with me.

**Comment by ktbyers** [comment]
I will try to experiment some more with this shortly.

**Comment by ogenstad** [comment]
Now I want a filter to include all hosts from groupA, groupB or groupC. Should we have something for that or just write a custom function?

**Comment by dbarrosop** [comment]
to do that I was thinking in implement the `+` and `-` operation so you can do something like:

```
blah_or_bleh = nr.filter(my_var="blah") +  nr.filter(my_var="bleh")
```

**Comment by ogenstad** [comment]
Ah yes, remember that. Looks good.

**Comment by targuan** [comment]
I was thinking about proposing to implement django like or SQLAchemy like filtering but you beat me to it. I got stuck will wondering if this should be implemented natively in the inventory filtering system or as a helper in the plugins.

I started an [implementation](https://github.com/nornir-automation/nornir/compare/develop...targuan:feature/filter_helper) more like the [Q object](https://docs.djangoproject.com/en/2.0/topics/db/queries/#complex-lookups-with-q-objects) in django and use it as a func_filter:
```python
f = F(site="site1")
nornir.filter(filter_func=f.match)
```
I thought it allowed more complexe/lighter filtering than just combination operations on arrays:
```python
f = F(groups__contains="group1") & (F(role="www") | F(site__in=["site1","site2"]))
nornir.filter(filter_func=f.match)
```

**Comment by ktbyers** [comment]
Somewhat related to @targuan comments, but should the operations/operators be set operations (unions, intersections, difference, et cetera).

**Comment by dbarrosop** [comment]
Regarding set operations I agree, if you check the last commit I pushed that’s actually what I ended up implemented.

Regarding @targuan’s suggestion I like it a lot so I’d suggest closing this PR and working on his idea. How far are you in the implementation?

thoughts?

**Comment by targuan** [comment]
I have the basic filtering (ie ```__eq__```),  ```and```, ```or``` and ```invert``` operators.
If you allow me to integrate your verify_rules logic, I will also have the \__*\__ operators.

**Comment by dbarrosop** [comment]
Closing in favor of #155

**Pull request closed without merging**
