### PR TITLE
Severity_level was override when task is flag as failed

### PR DESCRIPTION
**Pull request by FloLaco**
Issue related: #609

Severity_level precedence : 

- return `Result(severity_level=XXX)` (top priority)
- if task is failed : `ERROR` if no return `Result(severity_level=XXX)`
- severity_level set in `nornir.run(severity_level)`
- `INFO` (`DEFAULT_SEVERITY_LEVEL`) (less priority)

I.E.

```
        return Result(
            host=task.host,
            failed=True,
            result=f"syslog cannot be configured {task.host.name}."

result = nr.run(
    task=configure_logging,
)
```

Result : 
```
configure_logging***************************************************************
* host ** changed : False *********************************************
vvvv configure_logging ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
syslog cannot be configured host.
---- Add the syslog host ** changed : False ------------------------------------ INFO
```

____

```
        return Result(
            host=task.host,
            failed=True,
            result=f"syslog cannot be configured {task.host.name}."
        )

result = nr.run(
    task=configure_logging,
    severity_level=logging.WARN
)
```

Result : 
```
vvvv configure_logging ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
syslog cannot be configured host.
---- Add the syslog host ** changed : False ------------------------------------ WARNING
```

____

```
        return Result(
            host=task.host,
            failed=True,
            severity_level=logging.CRITICAL,
            result=f"syslog cannot be configured {task.host.name}."
        )

result = nr.run(
    task=configure_logging,
)
```

Result :
```
vvvv configure_logging ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv CRITICAL
syslog cannot be configured host.
---- Add the syslog host ** changed : False ------------------------------------ INFO
```

____

```
        return Result(
            host=task.host,
            failed=True,
            severity_level=logging.CRITICAL,
            result=f"syslog cannot be configured {task.host.name}."
        )

result = nr.run(
    task=configure_logging,
    severity_level=logging.WARN
)
```

Result : 
```
vvvv configure_logging ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv CRITICAL
syslog cannot be configured host.
---- Add the syslog host ** changed : False ------------------------------------ WARNING
```

### CODE REVIEW

**Comment by FloLaco** [comment]
@dbarrosop Do you know why github pipeline failed (about poetry) ? Do I need to change something before commit ?

**Comment by dbarrosop** [comment]
Problem is that GitHub actions deprecated a facility one of the actions was using and needed to be updated. I just fixed so it should work now.

**Comment by dbarrosop** [comment]
Tests look good now but the linter is mildly unhappy. Once that is fixed I will merge as, otherwise, the PR is good.

Thanks and good job! :)

**Comment by FloLaco** [comment]
@dbarrosop I've fixed the linter and the formatting with black and change the doc because "Exception traceback" was not the same because the line number changed.

**Comment by dbarrosop** [comment]
thanks, windows build is broken but it is unrelated to the PR so I am merging regardless. Thanks again!

**Pull request merged**
