### PR TITLE
pinned pydantic

### PR DESCRIPTION
**Pull request by dbarrosop**

### CODE REVIEW

**Comment by dmfigol** [comment]
The builds fails because of the incorrect type signature in `ruamel.yaml 0.16.6` this was fixed in the latest 0.16.7

**Comment by dmfigol** [comment]
@dbarrosop can you retrigger ci build? closing/opening PR does not trigger ci anymore :(

**Comment by ktbyers** [comment]
It let me do "Restart Build" in Travis-CI so I just did it there.

**Comment by dbarrosop** [comment]
I don't seem to be able to retrigger the build for the PR. The option doesn't show. I will open a new one

**Comment by dbarrosop** [comment]
Replaced by #482

**Pull request closed without merging**
