### PR TITLE
Add netbox inventory plugin tag support #496

### PR DESCRIPTION
**Pull request by egreenspan2**
Get NetBox tags array into Nornir, updated test devices with tags to validate, per #496  (novice developer, be gentle)

### CODE REVIEW

**Comment by ktbyers** [comment]
@egreenspan2 We are moving towards an external plugin model for plugins like the Netbox plugin. I believe a set of other people were already doing a bunch of work on an updated Netbox plugin. Let me see if I can connect you to them.

**Comment by ktbyers** [comment]
@clay584 you were working on the new Netbox plugin correct?

**Comment by clay584** [comment]
Yes. Myself and @wvandeun

**Comment by wvandeun** [comment]
#479 contains all of the work for tags (and other attributes already).
It will map all of the applied tags for a device into the Nornir host data attribute.

**Comment by egreenspan2** [comment]
> 
> 
> #479 contains all of the work for tags (and other attributes already).
> It will map all of the applied tags for a device into the Nornir host data attribute.

Makes more sense now, will start testing with new plugin.  I'll close this out.

**Pull request closed without merging**
