### PR TITLE
napalm rollback task and testing

### PR DESCRIPTION
**Pull request by jchristopher327**
Giving this another attempt (previously at #387)
Implements #386

### CODE REVIEW

**Comment by ktbyers** [comment]
We should relocate this to the `nornir_napalm` repository so that it is part of Nornir 3.X:

https://github.com/nornir-automation/nornir_napalm/

**Comment by jchristopher327** [comment]
Ok, I'll close this one out and create the PR in the `nornir_napalm` repository.

**Comment by ktbyers** [comment]
Sounds good.

**Comment by jchristopher327** [comment]
https://github.com/nornir-automation/nornir_napalm/pull/6

**Pull request closed without merging**
