### PR TITLE
Temporary fix for enum34 and netmiko-poetry issue

### PR DESCRIPTION
**Pull request by ktbyers**
Testing if this fixes unit tests.

### CODE REVIEW

**Comment by bradh11** [comment]
Interesting.   What is the nbval test checking?   That change should be benign in terminal based usage.  Right?

**Comment by ktbyers** [comment]
@bradh11 The nbval test is testing some Python notebooks and actually looks at the exact output including color (so I think the color output has changed here).

**Comment by bradh11** [comment]
Is it testing via ipython or Jupyter (or other)?   I can do some research to see if different behavior is expected in that type of environment.

**Comment by ktbyers** [comment]
It is failing on these Jupyter Notebook's:

https://github.com/nornir-automation/nornir/tree/develop/docs/howto

This is the basis for parts of these docs:

https://nornir.readthedocs.io/en/stable/howto/handling_connections.html

**Comment by ktbyers** [comment]
@dbarrosop @dmfigol I think we should incorporate the pyproject.toml and .lock file fixes specified here so that the tests and the development environment start working again.

This will give me additional time to get a new Netmiko release pushed to pypi.

Not sure what we want to do about the colorama issue i.e. whether we want to roll it back here (so the tests start working again)? I only looked at the colorama issue briefly.

**Comment by dbarrosop** [comment]
> Not sure what we want to do about the colorama issue i.e. whether we want to roll it back here (so the tests start working again)?

Yes, let's revert it and investigate in parallel. @bradh11 can you do that?

> This will give me additional time to get a new Netmiko release pushed to pypi.

LGTM

**Comment by bradh11** [comment]
I probably wont have time to get to it until end of the week, but yes I can research it and let you know my findings.  Can you re-open 319?

**Comment by dbarrosop** [comment]
Thanks, just reopened it.

**Comment by dmfigol** [comment]
LGTM

**Pull request merged**
