### PR TITLE
Update Apache-2.0 in pyproject.toml

### PR DESCRIPTION
**Pull request by dgarros**
I think this should fix the issue in Pypi reported by #975 

https://python-poetry.org/docs/pyproject/#license

### CODE REVIEW

**Comment by ktbyers** [comment]
@dgarros Can you also switch the classifier to:

License :: OSI Approved :: Apache Software License 2.0 (Apache-2.0)

In pyproject.toml

See:

https://github.com/pypa/trove-classifiers/issues/17

**Comment by dgarros** [comment]
> @dgarros Can you also switch the classifier to:
> 
> License :: OSI Approved :: Apache Software License 2.0 (Apache-2.0)

Done

**Review by ktbyers — APPROVED** [review]

**Comment by ktbyers** [comment]
FYI, the second part of this didn't work i.e. pypi rejected it:

```
WARNING  Error during upload. Retry with the --verbose option for more details.                                                     
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                            
         'License :: OSI Approved :: Apache Software License 2.0 (Apache-2.0)' is not a valid classifier. See                       
         https://packaging.python.org/specifications/core-metadata for more information.
```

Also the classifier never accepted the change that was in the referenced issue (see):

https://github.com/pypa/trove-classifiers/blob/main/src/trove_classifiers/__init__.py#L283

So I am going to revert this part of the PR.

**Comment by ktbyers** [comment]
I checked both the METADATA file and the PKG-INFO file and the Properietary License referfence was gone (after reverting the classifier part of this.

So adding the hyphen was sufficient to fix the original issue.

**Comment by ktbyers** [comment]
@dbarrosop @ogenstad Should be a quick review/approval.

**Pull request merged**
