### PR TITLE
Allow setting of attribute for nornir_ attributes

### PR DESCRIPTION
**Pull request by ktbyers**
Do Not Merge:

Allow the nornir_ attributes that are using @property to have a setter.

This would allow you to do:

```
nornir_host.username = 'whatever'
nornir_host.password = getpass()
```

Could also implement using the @property .setter format if that is preferred.

If this looks reasonable, I will update and add unit tests (add cleanup changes unrelated to `__setattr__`).

### CODE REVIEW

**Comment by dbarrosop** [comment]
Thanks. Can we use the `@property.setter` as you suggest though?

**Comment by dmfigol** [comment]
Makes perfect sense!
+1 to `@property.setter`

**Comment by ktbyers** [comment]
That is fine. I had `@property.setter` here so I will just rollback to that:

https://github.com/nornir-automation/nornir/pull/200/commits/d97fc0ca552a7f5b2e70218b30336c60ed04be10

**Comment by dbarrosop** [comment]
I guess we can hold onto this one until we close #202

**Pull request closed without merging**
